/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 35.4.0 Wed Nov 11 21:32:39 2020.
 */

#include <string.h>

#include "CAN0.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int CAN0_tcgps_11_pack(
    uint8_t *dst_p,
    const struct CAN0_tcgps_11_t *src_p,
    size_t size)
{
    uint8_t tcgps_laptrigger;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    tcgps_laptrigger = (uint8_t)src_p->tcgps_laptrigger;
    dst_p[0] |= pack_left_shift_u8(tcgps_laptrigger, 0u, 0xffu);

    return (8);
}

int CAN0_tcgps_11_unpack(
    struct CAN0_tcgps_11_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t tcgps_laptrigger;

    if (size < 8u) {
        return (-EINVAL);
    }

    tcgps_laptrigger = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->tcgps_laptrigger = (int8_t)tcgps_laptrigger;

    return (0);
}

int8_t CAN0_tcgps_11_tcgps_laptrigger_encode(double value)
{
    return (int8_t)(value);
}

double CAN0_tcgps_11_tcgps_laptrigger_decode(int8_t value)
{
    return ((double)value);
}

bool CAN0_tcgps_11_tcgps_laptrigger_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int CAN0_mm5_02_pack(
    uint8_t *dst_p,
    const struct CAN0_mm5_02_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[4] |= pack_left_shift_u16(src_p->mm5_az, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->mm5_az, 8u, 0xffu);

    return (8);
}

int CAN0_mm5_02_unpack(
    struct CAN0_mm5_02_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->mm5_az = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->mm5_az |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

uint16_t CAN0_mm5_02_mm5_az_encode(double value)
{
    return (uint16_t)((value - -4.1745795) / -0.0001274);
}

double CAN0_mm5_02_mm5_az_decode(uint16_t value)
{
    return (((double)value * -0.0001274) + -4.1745795);
}

bool CAN0_mm5_02_mm5_az_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int CAN0_mm5_01_pack(
    uint8_t *dst_p,
    const struct CAN0_mm5_01_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->mm5_roll_rate, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->mm5_roll_rate, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->mm5_ax, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->mm5_ax, 8u, 0xffu);

    return (8);
}

int CAN0_mm5_01_unpack(
    struct CAN0_mm5_01_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->mm5_roll_rate = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->mm5_roll_rate |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->mm5_ax = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->mm5_ax |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

uint16_t CAN0_mm5_01_mm5_roll_rate_encode(double value)
{
    return (uint16_t)((value - 163.9) / -0.005);
}

double CAN0_mm5_01_mm5_roll_rate_decode(uint16_t value)
{
    return (((double)value * -0.005) + 163.9);
}

bool CAN0_mm5_01_mm5_roll_rate_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t CAN0_mm5_01_mm5_ax_encode(double value)
{
    return (uint16_t)((value - 4.1745795) / -0.0001274);
}

double CAN0_mm5_01_mm5_ax_decode(uint16_t value)
{
    return (((double)value * -0.0001274) + 4.1745795);
}

bool CAN0_mm5_01_mm5_ax_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int CAN0_mm5_00_pack(
    uint8_t *dst_p,
    const struct CAN0_mm5_00_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->mm5_yaw_rate, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->mm5_yaw_rate, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->mm5_ay, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->mm5_ay, 8u, 0xffu);

    return (8);
}

int CAN0_mm5_00_unpack(
    struct CAN0_mm5_00_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->mm5_yaw_rate = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->mm5_yaw_rate |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->mm5_ay = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->mm5_ay |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

uint16_t CAN0_mm5_00_mm5_yaw_rate_encode(double value)
{
    return (uint16_t)((value - -163.9) / 0.005);
}

double CAN0_mm5_00_mm5_yaw_rate_decode(uint16_t value)
{
    return (((double)value * 0.005) + -163.9);
}

bool CAN0_mm5_00_mm5_yaw_rate_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t CAN0_mm5_00_mm5_ay_encode(double value)
{
    return (uint16_t)((value - 4.1745795) / -0.0001274);
}

double CAN0_mm5_00_mm5_ay_decode(uint16_t value)
{
    return (((double)value * -0.0001274) + 4.1745795);
}

bool CAN0_mm5_00_mm5_ay_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int CAN0_m400_data_set2_pack(
    uint8_t *dst_p,
    const struct CAN0_m400_data_set2_t *src_p,
    size_t size)
{
    uint16_t m400_aux_out1_duty_cycle;
    uint16_t m400_aux_out2_duty_cycle;
    uint16_t m400_aux_out3_duty_cycle;
    uint16_t m400_aux_out4_duty_cycle;
    uint16_t m400_aux_out5_duty_cycle;
    uint16_t m400_aux_out6_duty_cycle;
    uint16_t m400_aux_out7_duty_cycle;
    uint16_t m400_aux_out8_duty_cycle;
    uint16_t m400_battery_voltage;
    uint16_t m400_ecu_cpu_usage;
    uint16_t m400_ecu_internal_temp;
    uint16_t m400_engine_temp;
    uint16_t m400_exhaust_gas_temp1;
    uint16_t m400_exhaust_gas_temp2;
    uint16_t m400_exhaust_gas_temp3;
    uint16_t m400_exhaust_gas_temp4;
    uint16_t m400_fuel1_indiv_trim;
    uint16_t m400_fuel2_indiv_trim;
    uint16_t m400_fuel3_indiv_trim;
    uint16_t m400_fuel4_indiv_trim;
    uint16_t m400_fuel_actual_pulse_w;
    uint16_t m400_fuel_at_comp;
    uint16_t m400_fuel_comp1;
    uint16_t m400_fuel_comp2;
    uint16_t m400_fuel_et_comp;
    uint16_t m400_fuel_fp_comp;
    uint16_t m400_fuel_ft_comp;
    uint16_t m400_fuel_inj_duty_cycle;
    uint16_t m400_fuel_lambda_comp;
    uint16_t m400_fuel_map_comp;
    uint16_t m400_fuel_pressure;
    uint16_t m400_fuel_starting_comp;
    uint16_t m400_fuel_temp;
    uint16_t m400_fuel_used;
    uint16_t m400_ign1_advance;
    uint16_t m400_ign2_advance;
    uint16_t m400_ign3_advance;
    uint16_t m400_ign4_advance;
    uint16_t m400_ign_at_comp;
    uint16_t m400_ign_base_advance;
    uint16_t m400_ign_comp1;
    uint16_t m400_ign_comp2;
    uint16_t m400_ign_et_comp;
    uint16_t m400_ign_map_comp;
    uint16_t m400_inlet_air_temp;
    uint16_t m400_la1_long_term_trim;
    uint16_t m400_manifold_pressure;
    uint16_t m400_oil_pressure;
    uint16_t m400_oil_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->m400_row_counter_data_set2, 0u, 0xffu);

    switch (src_p->m400_row_counter_data_set2) {

    case 0:
        m400_aux_out1_duty_cycle = (uint16_t)src_p->m400_aux_out1_duty_cycle;
        dst_p[2] |= pack_right_shift_u16(m400_aux_out1_duty_cycle, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_aux_out1_duty_cycle, 0u, 0xffu);
        m400_aux_out2_duty_cycle = (uint16_t)src_p->m400_aux_out2_duty_cycle;
        dst_p[4] |= pack_right_shift_u16(m400_aux_out2_duty_cycle, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_aux_out2_duty_cycle, 0u, 0xffu);
        m400_aux_out3_duty_cycle = (uint16_t)src_p->m400_aux_out3_duty_cycle;
        dst_p[6] |= pack_right_shift_u16(m400_aux_out3_duty_cycle, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_aux_out3_duty_cycle, 0u, 0xffu);
        break;

    case 1:
        m400_aux_out4_duty_cycle = (uint16_t)src_p->m400_aux_out4_duty_cycle;
        dst_p[2] |= pack_right_shift_u16(m400_aux_out4_duty_cycle, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_aux_out4_duty_cycle, 0u, 0xffu);
        m400_aux_out5_duty_cycle = (uint16_t)src_p->m400_aux_out5_duty_cycle;
        dst_p[4] |= pack_right_shift_u16(m400_aux_out5_duty_cycle, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_aux_out5_duty_cycle, 0u, 0xffu);
        m400_aux_out6_duty_cycle = (uint16_t)src_p->m400_aux_out6_duty_cycle;
        dst_p[6] |= pack_right_shift_u16(m400_aux_out6_duty_cycle, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_aux_out6_duty_cycle, 0u, 0xffu);
        break;

    case 2:
        m400_aux_out7_duty_cycle = (uint16_t)src_p->m400_aux_out7_duty_cycle;
        dst_p[2] |= pack_right_shift_u16(m400_aux_out7_duty_cycle, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_aux_out7_duty_cycle, 0u, 0xffu);
        m400_aux_out8_duty_cycle = (uint16_t)src_p->m400_aux_out8_duty_cycle;
        dst_p[4] |= pack_right_shift_u16(m400_aux_out8_duty_cycle, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_aux_out8_duty_cycle, 0u, 0xffu);
        m400_battery_voltage = (uint16_t)src_p->m400_battery_voltage;
        dst_p[6] |= pack_right_shift_u16(m400_battery_voltage, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_battery_voltage, 0u, 0xffu);
        break;

    case 3:
        m400_ecu_cpu_usage = (uint16_t)src_p->m400_ecu_cpu_usage;
        dst_p[2] |= pack_right_shift_u16(m400_ecu_cpu_usage, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_ecu_cpu_usage, 0u, 0xffu);
        m400_ecu_internal_temp = (uint16_t)src_p->m400_ecu_internal_temp;
        dst_p[4] |= pack_right_shift_u16(m400_ecu_internal_temp, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_ecu_internal_temp, 0u, 0xffu);
        m400_engine_temp = (uint16_t)src_p->m400_engine_temp;
        dst_p[6] |= pack_right_shift_u16(m400_engine_temp, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_engine_temp, 0u, 0xffu);
        break;

    case 4:
        m400_exhaust_gas_temp1 = (uint16_t)src_p->m400_exhaust_gas_temp1;
        dst_p[2] |= pack_right_shift_u16(m400_exhaust_gas_temp1, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_exhaust_gas_temp1, 0u, 0xffu);
        m400_exhaust_gas_temp2 = (uint16_t)src_p->m400_exhaust_gas_temp2;
        dst_p[4] |= pack_right_shift_u16(m400_exhaust_gas_temp2, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_exhaust_gas_temp2, 0u, 0xffu);
        m400_exhaust_gas_temp3 = (uint16_t)src_p->m400_exhaust_gas_temp3;
        dst_p[6] |= pack_right_shift_u16(m400_exhaust_gas_temp3, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_exhaust_gas_temp3, 0u, 0xffu);
        break;

    case 5:
        m400_exhaust_gas_temp4 = (uint16_t)src_p->m400_exhaust_gas_temp4;
        dst_p[2] |= pack_right_shift_u16(m400_exhaust_gas_temp4, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_exhaust_gas_temp4, 0u, 0xffu);
        m400_fuel1_indiv_trim = (uint16_t)src_p->m400_fuel1_indiv_trim;
        dst_p[4] |= pack_right_shift_u16(m400_fuel1_indiv_trim, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_fuel1_indiv_trim, 0u, 0xffu);
        m400_fuel2_indiv_trim = (uint16_t)src_p->m400_fuel2_indiv_trim;
        dst_p[6] |= pack_right_shift_u16(m400_fuel2_indiv_trim, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_fuel2_indiv_trim, 0u, 0xffu);
        break;

    case 6:
        m400_fuel3_indiv_trim = (uint16_t)src_p->m400_fuel3_indiv_trim;
        dst_p[2] |= pack_right_shift_u16(m400_fuel3_indiv_trim, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_fuel3_indiv_trim, 0u, 0xffu);
        m400_fuel4_indiv_trim = (uint16_t)src_p->m400_fuel4_indiv_trim;
        dst_p[4] |= pack_right_shift_u16(m400_fuel4_indiv_trim, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_fuel4_indiv_trim, 0u, 0xffu);
        m400_fuel_actual_pulse_w = (uint16_t)src_p->m400_fuel_actual_pulse_w;
        dst_p[6] |= pack_right_shift_u16(m400_fuel_actual_pulse_w, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_fuel_actual_pulse_w, 0u, 0xffu);
        break;

    case 7:
        m400_fuel_at_comp = (uint16_t)src_p->m400_fuel_at_comp;
        dst_p[2] |= pack_right_shift_u16(m400_fuel_at_comp, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_fuel_at_comp, 0u, 0xffu);
        m400_fuel_comp1 = (uint16_t)src_p->m400_fuel_comp1;
        dst_p[4] |= pack_right_shift_u16(m400_fuel_comp1, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_fuel_comp1, 0u, 0xffu);
        m400_fuel_comp2 = (uint16_t)src_p->m400_fuel_comp2;
        dst_p[6] |= pack_right_shift_u16(m400_fuel_comp2, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_fuel_comp2, 0u, 0xffu);
        break;

    case 8:
        m400_fuel_et_comp = (uint16_t)src_p->m400_fuel_et_comp;
        dst_p[2] |= pack_right_shift_u16(m400_fuel_et_comp, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_fuel_et_comp, 0u, 0xffu);
        m400_fuel_fp_comp = (uint16_t)src_p->m400_fuel_fp_comp;
        dst_p[4] |= pack_right_shift_u16(m400_fuel_fp_comp, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_fuel_fp_comp, 0u, 0xffu);
        m400_fuel_ft_comp = (uint16_t)src_p->m400_fuel_ft_comp;
        dst_p[6] |= pack_right_shift_u16(m400_fuel_ft_comp, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_fuel_ft_comp, 0u, 0xffu);
        break;

    case 9:
        m400_fuel_inj_duty_cycle = (uint16_t)src_p->m400_fuel_inj_duty_cycle;
        dst_p[2] |= pack_right_shift_u16(m400_fuel_inj_duty_cycle, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_fuel_inj_duty_cycle, 0u, 0xffu);
        m400_fuel_lambda_comp = (uint16_t)src_p->m400_fuel_lambda_comp;
        dst_p[4] |= pack_right_shift_u16(m400_fuel_lambda_comp, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_fuel_lambda_comp, 0u, 0xffu);
        m400_fuel_map_comp = (uint16_t)src_p->m400_fuel_map_comp;
        dst_p[6] |= pack_right_shift_u16(m400_fuel_map_comp, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_fuel_map_comp, 0u, 0xffu);
        break;

    case 10:
        m400_fuel_pressure = (uint16_t)src_p->m400_fuel_pressure;
        dst_p[2] |= pack_right_shift_u16(m400_fuel_pressure, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_fuel_pressure, 0u, 0xffu);
        m400_fuel_starting_comp = (uint16_t)src_p->m400_fuel_starting_comp;
        dst_p[4] |= pack_right_shift_u16(m400_fuel_starting_comp, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_fuel_starting_comp, 0u, 0xffu);
        m400_fuel_temp = (uint16_t)src_p->m400_fuel_temp;
        dst_p[6] |= pack_right_shift_u16(m400_fuel_temp, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_fuel_temp, 0u, 0xffu);
        break;

    case 11:
        m400_fuel_used = (uint16_t)src_p->m400_fuel_used;
        dst_p[2] |= pack_right_shift_u16(m400_fuel_used, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_fuel_used, 0u, 0xffu);
        m400_ign1_advance = (uint16_t)src_p->m400_ign1_advance;
        dst_p[4] |= pack_right_shift_u16(m400_ign1_advance, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_ign1_advance, 0u, 0xffu);
        m400_ign2_advance = (uint16_t)src_p->m400_ign2_advance;
        dst_p[6] |= pack_right_shift_u16(m400_ign2_advance, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_ign2_advance, 0u, 0xffu);
        break;

    case 12:
        m400_ign3_advance = (uint16_t)src_p->m400_ign3_advance;
        dst_p[2] |= pack_right_shift_u16(m400_ign3_advance, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_ign3_advance, 0u, 0xffu);
        m400_ign4_advance = (uint16_t)src_p->m400_ign4_advance;
        dst_p[4] |= pack_right_shift_u16(m400_ign4_advance, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_ign4_advance, 0u, 0xffu);
        m400_ign_at_comp = (uint16_t)src_p->m400_ign_at_comp;
        dst_p[6] |= pack_right_shift_u16(m400_ign_at_comp, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_ign_at_comp, 0u, 0xffu);
        break;

    case 13:
        m400_ign_base_advance = (uint16_t)src_p->m400_ign_base_advance;
        dst_p[2] |= pack_right_shift_u16(m400_ign_base_advance, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_ign_base_advance, 0u, 0xffu);
        m400_ign_comp1 = (uint16_t)src_p->m400_ign_comp1;
        dst_p[4] |= pack_right_shift_u16(m400_ign_comp1, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_ign_comp1, 0u, 0xffu);
        m400_ign_comp2 = (uint16_t)src_p->m400_ign_comp2;
        dst_p[6] |= pack_right_shift_u16(m400_ign_comp2, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_ign_comp2, 0u, 0xffu);
        break;

    case 14:
        m400_ign_et_comp = (uint16_t)src_p->m400_ign_et_comp;
        dst_p[2] |= pack_right_shift_u16(m400_ign_et_comp, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_ign_et_comp, 0u, 0xffu);
        m400_ign_map_comp = (uint16_t)src_p->m400_ign_map_comp;
        dst_p[4] |= pack_right_shift_u16(m400_ign_map_comp, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_ign_map_comp, 0u, 0xffu);
        m400_inlet_air_temp = (uint16_t)src_p->m400_inlet_air_temp;
        dst_p[6] |= pack_right_shift_u16(m400_inlet_air_temp, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_inlet_air_temp, 0u, 0xffu);
        break;

    case 15:
        m400_la1_long_term_trim = (uint16_t)src_p->m400_la1_long_term_trim;
        dst_p[2] |= pack_right_shift_u16(m400_la1_long_term_trim, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_la1_long_term_trim, 0u, 0xffu);
        m400_manifold_pressure = (uint16_t)src_p->m400_manifold_pressure;
        dst_p[4] |= pack_right_shift_u16(m400_manifold_pressure, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_manifold_pressure, 0u, 0xffu);
        m400_oil_pressure = (uint16_t)src_p->m400_oil_pressure;
        dst_p[6] |= pack_right_shift_u16(m400_oil_pressure, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_oil_pressure, 0u, 0xffu);
        break;

    case 16:
        m400_oil_temp = (uint16_t)src_p->m400_oil_temp;
        dst_p[2] |= pack_right_shift_u16(m400_oil_temp, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_oil_temp, 0u, 0xffu);
        break;

    default:
        break;
    }

    return (8);
}

int CAN0_m400_data_set2_unpack(
    struct CAN0_m400_data_set2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t m400_aux_out1_duty_cycle;
    uint16_t m400_aux_out2_duty_cycle;
    uint16_t m400_aux_out3_duty_cycle;
    uint16_t m400_aux_out4_duty_cycle;
    uint16_t m400_aux_out5_duty_cycle;
    uint16_t m400_aux_out6_duty_cycle;
    uint16_t m400_aux_out7_duty_cycle;
    uint16_t m400_aux_out8_duty_cycle;
    uint16_t m400_battery_voltage;
    uint16_t m400_ecu_cpu_usage;
    uint16_t m400_ecu_internal_temp;
    uint16_t m400_engine_temp;
    uint16_t m400_exhaust_gas_temp1;
    uint16_t m400_exhaust_gas_temp2;
    uint16_t m400_exhaust_gas_temp3;
    uint16_t m400_exhaust_gas_temp4;
    uint16_t m400_fuel1_indiv_trim;
    uint16_t m400_fuel2_indiv_trim;
    uint16_t m400_fuel3_indiv_trim;
    uint16_t m400_fuel4_indiv_trim;
    uint16_t m400_fuel_actual_pulse_w;
    uint16_t m400_fuel_at_comp;
    uint16_t m400_fuel_comp1;
    uint16_t m400_fuel_comp2;
    uint16_t m400_fuel_et_comp;
    uint16_t m400_fuel_fp_comp;
    uint16_t m400_fuel_ft_comp;
    uint16_t m400_fuel_inj_duty_cycle;
    uint16_t m400_fuel_lambda_comp;
    uint16_t m400_fuel_map_comp;
    uint16_t m400_fuel_pressure;
    uint16_t m400_fuel_starting_comp;
    uint16_t m400_fuel_temp;
    uint16_t m400_fuel_used;
    uint16_t m400_ign1_advance;
    uint16_t m400_ign2_advance;
    uint16_t m400_ign3_advance;
    uint16_t m400_ign4_advance;
    uint16_t m400_ign_at_comp;
    uint16_t m400_ign_base_advance;
    uint16_t m400_ign_comp1;
    uint16_t m400_ign_comp2;
    uint16_t m400_ign_et_comp;
    uint16_t m400_ign_map_comp;
    uint16_t m400_inlet_air_temp;
    uint16_t m400_la1_long_term_trim;
    uint16_t m400_manifold_pressure;
    uint16_t m400_oil_pressure;
    uint16_t m400_oil_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->m400_row_counter_data_set2 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    switch (dst_p->m400_row_counter_data_set2) {

    case 0:
        m400_aux_out1_duty_cycle = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_aux_out1_duty_cycle |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_aux_out1_duty_cycle = (int16_t)m400_aux_out1_duty_cycle;
        m400_aux_out2_duty_cycle = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_aux_out2_duty_cycle |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_aux_out2_duty_cycle = (int16_t)m400_aux_out2_duty_cycle;
        m400_aux_out3_duty_cycle = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_aux_out3_duty_cycle |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_aux_out3_duty_cycle = (int16_t)m400_aux_out3_duty_cycle;
        break;

    case 1:
        m400_aux_out4_duty_cycle = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_aux_out4_duty_cycle |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_aux_out4_duty_cycle = (int16_t)m400_aux_out4_duty_cycle;
        m400_aux_out5_duty_cycle = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_aux_out5_duty_cycle |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_aux_out5_duty_cycle = (int16_t)m400_aux_out5_duty_cycle;
        m400_aux_out6_duty_cycle = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_aux_out6_duty_cycle |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_aux_out6_duty_cycle = (int16_t)m400_aux_out6_duty_cycle;
        break;

    case 2:
        m400_aux_out7_duty_cycle = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_aux_out7_duty_cycle |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_aux_out7_duty_cycle = (int16_t)m400_aux_out7_duty_cycle;
        m400_aux_out8_duty_cycle = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_aux_out8_duty_cycle |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_aux_out8_duty_cycle = (int16_t)m400_aux_out8_duty_cycle;
        m400_battery_voltage = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_battery_voltage |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_battery_voltage = (int16_t)m400_battery_voltage;
        break;

    case 3:
        m400_ecu_cpu_usage = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_ecu_cpu_usage |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_ecu_cpu_usage = (int16_t)m400_ecu_cpu_usage;
        m400_ecu_internal_temp = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_ecu_internal_temp |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_ecu_internal_temp = (int16_t)m400_ecu_internal_temp;
        m400_engine_temp = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_engine_temp |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_engine_temp = (int16_t)m400_engine_temp;
        break;

    case 4:
        m400_exhaust_gas_temp1 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_exhaust_gas_temp1 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_exhaust_gas_temp1 = (int16_t)m400_exhaust_gas_temp1;
        m400_exhaust_gas_temp2 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_exhaust_gas_temp2 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_exhaust_gas_temp2 = (int16_t)m400_exhaust_gas_temp2;
        m400_exhaust_gas_temp3 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_exhaust_gas_temp3 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_exhaust_gas_temp3 = (int16_t)m400_exhaust_gas_temp3;
        break;

    case 5:
        m400_exhaust_gas_temp4 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_exhaust_gas_temp4 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_exhaust_gas_temp4 = (int16_t)m400_exhaust_gas_temp4;
        m400_fuel1_indiv_trim = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_fuel1_indiv_trim |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_fuel1_indiv_trim = (int16_t)m400_fuel1_indiv_trim;
        m400_fuel2_indiv_trim = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_fuel2_indiv_trim |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_fuel2_indiv_trim = (int16_t)m400_fuel2_indiv_trim;
        break;

    case 6:
        m400_fuel3_indiv_trim = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_fuel3_indiv_trim |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_fuel3_indiv_trim = (int16_t)m400_fuel3_indiv_trim;
        m400_fuel4_indiv_trim = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_fuel4_indiv_trim |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_fuel4_indiv_trim = (int16_t)m400_fuel4_indiv_trim;
        m400_fuel_actual_pulse_w = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_fuel_actual_pulse_w |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_fuel_actual_pulse_w = (int16_t)m400_fuel_actual_pulse_w;
        break;

    case 7:
        m400_fuel_at_comp = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_fuel_at_comp |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_fuel_at_comp = (int16_t)m400_fuel_at_comp;
        m400_fuel_comp1 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_fuel_comp1 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_fuel_comp1 = (int16_t)m400_fuel_comp1;
        m400_fuel_comp2 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_fuel_comp2 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_fuel_comp2 = (int16_t)m400_fuel_comp2;
        break;

    case 8:
        m400_fuel_et_comp = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_fuel_et_comp |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_fuel_et_comp = (int16_t)m400_fuel_et_comp;
        m400_fuel_fp_comp = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_fuel_fp_comp |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_fuel_fp_comp = (int16_t)m400_fuel_fp_comp;
        m400_fuel_ft_comp = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_fuel_ft_comp |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_fuel_ft_comp = (int16_t)m400_fuel_ft_comp;
        break;

    case 9:
        m400_fuel_inj_duty_cycle = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_fuel_inj_duty_cycle |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_fuel_inj_duty_cycle = (int16_t)m400_fuel_inj_duty_cycle;
        m400_fuel_lambda_comp = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_fuel_lambda_comp |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_fuel_lambda_comp = (int16_t)m400_fuel_lambda_comp;
        m400_fuel_map_comp = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_fuel_map_comp |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_fuel_map_comp = (int16_t)m400_fuel_map_comp;
        break;

    case 10:
        m400_fuel_pressure = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_fuel_pressure |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_fuel_pressure = (int16_t)m400_fuel_pressure;
        m400_fuel_starting_comp = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_fuel_starting_comp |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_fuel_starting_comp = (int16_t)m400_fuel_starting_comp;
        m400_fuel_temp = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_fuel_temp |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_fuel_temp = (int16_t)m400_fuel_temp;
        break;

    case 11:
        m400_fuel_used = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_fuel_used |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_fuel_used = (int16_t)m400_fuel_used;
        m400_ign1_advance = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_ign1_advance |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_ign1_advance = (int16_t)m400_ign1_advance;
        m400_ign2_advance = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_ign2_advance |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_ign2_advance = (int16_t)m400_ign2_advance;
        break;

    case 12:
        m400_ign3_advance = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_ign3_advance |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_ign3_advance = (int16_t)m400_ign3_advance;
        m400_ign4_advance = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_ign4_advance |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_ign4_advance = (int16_t)m400_ign4_advance;
        m400_ign_at_comp = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_ign_at_comp |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_ign_at_comp = (int16_t)m400_ign_at_comp;
        break;

    case 13:
        m400_ign_base_advance = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_ign_base_advance |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_ign_base_advance = (int16_t)m400_ign_base_advance;
        m400_ign_comp1 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_ign_comp1 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_ign_comp1 = (int16_t)m400_ign_comp1;
        m400_ign_comp2 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_ign_comp2 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_ign_comp2 = (int16_t)m400_ign_comp2;
        break;

    case 14:
        m400_ign_et_comp = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_ign_et_comp |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_ign_et_comp = (int16_t)m400_ign_et_comp;
        m400_ign_map_comp = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_ign_map_comp |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_ign_map_comp = (int16_t)m400_ign_map_comp;
        m400_inlet_air_temp = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_inlet_air_temp |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_inlet_air_temp = (int16_t)m400_inlet_air_temp;
        break;

    case 15:
        m400_la1_long_term_trim = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_la1_long_term_trim |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_la1_long_term_trim = (int16_t)m400_la1_long_term_trim;
        m400_manifold_pressure = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_manifold_pressure |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_manifold_pressure = (int16_t)m400_manifold_pressure;
        m400_oil_pressure = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_oil_pressure |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_oil_pressure = (int16_t)m400_oil_pressure;
        break;

    case 16:
        m400_oil_temp = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_oil_temp |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_oil_temp = (int16_t)m400_oil_temp;
        break;

    default:
        break;
    }

    return (0);
}

uint8_t CAN0_m400_data_set2_m400_row_counter_data_set2_encode(double value)
{
    return (uint8_t)(value);
}

double CAN0_m400_data_set2_m400_row_counter_data_set2_decode(uint8_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_row_counter_data_set2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_oil_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_oil_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_oil_temp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_la1_long_term_trim_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_la1_long_term_trim_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_la1_long_term_trim_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_ign_et_comp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_ign_et_comp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_ign_et_comp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_ign_base_advance_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_ign_base_advance_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_ign_base_advance_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_ign3_advance_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_ign3_advance_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_ign3_advance_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel_used_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_fuel_used_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_fuel_used_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel_pressure_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_fuel_pressure_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_fuel_pressure_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel_inj_duty_cycle_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_fuel_inj_duty_cycle_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_fuel_inj_duty_cycle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel_et_comp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_fuel_et_comp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_fuel_et_comp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel_at_comp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_fuel_at_comp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_fuel_at_comp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel3_indiv_trim_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_fuel3_indiv_trim_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_fuel3_indiv_trim_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_exhaust_gas_temp4_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_exhaust_gas_temp4_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_exhaust_gas_temp4_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_exhaust_gas_temp1_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_exhaust_gas_temp1_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_exhaust_gas_temp1_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_ecu_cpu_usage_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_ecu_cpu_usage_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_ecu_cpu_usage_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_aux_out7_duty_cycle_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_aux_out7_duty_cycle_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_aux_out7_duty_cycle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_aux_out4_duty_cycle_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_aux_out4_duty_cycle_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_aux_out4_duty_cycle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_aux_out1_duty_cycle_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_aux_out1_duty_cycle_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_aux_out1_duty_cycle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_manifold_pressure_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_manifold_pressure_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_manifold_pressure_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_ign_map_comp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_ign_map_comp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_ign_map_comp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_ign_comp1_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_ign_comp1_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_ign_comp1_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_ign4_advance_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_ign4_advance_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_ign4_advance_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_ign1_advance_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_ign1_advance_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_ign1_advance_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel_starting_comp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_fuel_starting_comp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_fuel_starting_comp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel_lambda_comp_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_fuel_lambda_comp_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_fuel_lambda_comp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel_fp_comp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_fuel_fp_comp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_fuel_fp_comp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel_comp1_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_fuel_comp1_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_fuel_comp1_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel4_indiv_trim_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_fuel4_indiv_trim_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_fuel4_indiv_trim_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel1_indiv_trim_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_fuel1_indiv_trim_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_fuel1_indiv_trim_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_exhaust_gas_temp2_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_exhaust_gas_temp2_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_exhaust_gas_temp2_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_ecu_internal_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_ecu_internal_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_ecu_internal_temp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_aux_out8_duty_cycle_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_aux_out8_duty_cycle_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_aux_out8_duty_cycle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_aux_out5_duty_cycle_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_aux_out5_duty_cycle_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_aux_out5_duty_cycle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_aux_out2_duty_cycle_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_aux_out2_duty_cycle_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_aux_out2_duty_cycle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_oil_pressure_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_oil_pressure_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_oil_pressure_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_inlet_air_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_inlet_air_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_inlet_air_temp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_ign_comp2_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_ign_comp2_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_ign_comp2_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_ign_at_comp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_ign_at_comp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_ign_at_comp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_ign2_advance_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_ign2_advance_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_ign2_advance_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_fuel_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_fuel_temp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel_map_comp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_fuel_map_comp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_fuel_map_comp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel_ft_comp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_fuel_ft_comp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_fuel_ft_comp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel_comp2_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_fuel_comp2_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_fuel_comp2_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel_actual_pulse_w_encode(double value)
{
    return (int16_t)(value / 0.002);
}

double CAN0_m400_data_set2_m400_fuel_actual_pulse_w_decode(int16_t value)
{
    return ((double)value * 0.002);
}

bool CAN0_m400_data_set2_m400_fuel_actual_pulse_w_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_fuel2_indiv_trim_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_fuel2_indiv_trim_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_fuel2_indiv_trim_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_exhaust_gas_temp3_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_exhaust_gas_temp3_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_exhaust_gas_temp3_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_engine_temp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set2_m400_engine_temp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set2_m400_engine_temp_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_battery_voltage_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double CAN0_m400_data_set2_m400_battery_voltage_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool CAN0_m400_data_set2_m400_battery_voltage_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_aux_out6_duty_cycle_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_aux_out6_duty_cycle_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_aux_out6_duty_cycle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set2_m400_aux_out3_duty_cycle_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set2_m400_aux_out3_duty_cycle_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set2_m400_aux_out3_duty_cycle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int CAN0_m400_data_set1_pack(
    uint8_t *dst_p,
    const struct CAN0_m400_data_set1_t *src_p,
    size_t size)
{
    uint16_t m400_drive_speed;
    uint16_t m400_drive_speed_left;
    uint16_t m400_drive_speed_right;
    uint16_t m400_fuel_cut_level_total;
    uint16_t m400_fuel_overall_trim;
    uint16_t m400_gear;
    uint16_t m400_gear_det;
    uint16_t m400_gear_sensor_voltage;
    uint16_t m400_ground_speed;
    uint16_t m400_ground_speed_left;
    uint16_t m400_ground_speed_right;
    uint16_t m400_ign_cut_level_total;
    uint16_t m400_ign_overall_trim;
    uint16_t m400_la1_aim_value;
    uint16_t m400_la1_short_term_trim;
    uint16_t m400_lambda1;
    uint16_t m400_rpm;
    uint16_t m400_tc_ignretard;
    uint16_t m400_tc_launch_aim_rpm;
    uint16_t m400_tc_power_reduction;
    uint16_t m400_tc_slip_aim_error;
    uint16_t m400_tc_slip_aim_value;
    uint16_t m400_throttle_position;
    uint16_t m400_wheel_slip;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->m400_row_counter_data_set1, 0u, 0xffu);

    switch (src_p->m400_row_counter_data_set1) {

    case 0:
        m400_drive_speed = (uint16_t)src_p->m400_drive_speed;
        dst_p[2] |= pack_right_shift_u16(m400_drive_speed, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_drive_speed, 0u, 0xffu);
        m400_drive_speed_left = (uint16_t)src_p->m400_drive_speed_left;
        dst_p[4] |= pack_right_shift_u16(m400_drive_speed_left, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_drive_speed_left, 0u, 0xffu);
        m400_drive_speed_right = (uint16_t)src_p->m400_drive_speed_right;
        dst_p[6] |= pack_right_shift_u16(m400_drive_speed_right, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_drive_speed_right, 0u, 0xffu);
        break;

    case 1:
        m400_ground_speed = (uint16_t)src_p->m400_ground_speed;
        dst_p[2] |= pack_right_shift_u16(m400_ground_speed, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_ground_speed, 0u, 0xffu);
        m400_ground_speed_left = (uint16_t)src_p->m400_ground_speed_left;
        dst_p[4] |= pack_right_shift_u16(m400_ground_speed_left, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_ground_speed_left, 0u, 0xffu);
        m400_ground_speed_right = (uint16_t)src_p->m400_ground_speed_right;
        dst_p[6] |= pack_right_shift_u16(m400_ground_speed_right, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_ground_speed_right, 0u, 0xffu);
        break;

    case 2:
        m400_tc_ignretard = (uint16_t)src_p->m400_tc_ignretard;
        dst_p[2] |= pack_right_shift_u16(m400_tc_ignretard, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_tc_ignretard, 0u, 0xffu);
        m400_tc_launch_aim_rpm = (uint16_t)src_p->m400_tc_launch_aim_rpm;
        dst_p[4] |= pack_right_shift_u16(m400_tc_launch_aim_rpm, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_tc_launch_aim_rpm, 0u, 0xffu);
        m400_tc_power_reduction = (uint16_t)src_p->m400_tc_power_reduction;
        dst_p[6] |= pack_right_shift_u16(m400_tc_power_reduction, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_tc_power_reduction, 0u, 0xffu);
        break;

    case 3:
        m400_tc_slip_aim_error = (uint16_t)src_p->m400_tc_slip_aim_error;
        dst_p[2] |= pack_right_shift_u16(m400_tc_slip_aim_error, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_tc_slip_aim_error, 0u, 0xffu);
        m400_tc_slip_aim_value = (uint16_t)src_p->m400_tc_slip_aim_value;
        dst_p[4] |= pack_right_shift_u16(m400_tc_slip_aim_value, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_tc_slip_aim_value, 0u, 0xffu);
        m400_wheel_slip = (uint16_t)src_p->m400_wheel_slip;
        dst_p[6] |= pack_right_shift_u16(m400_wheel_slip, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_wheel_slip, 0u, 0xffu);
        break;

    case 4:
        m400_ign_cut_level_total = (uint16_t)src_p->m400_ign_cut_level_total;
        dst_p[2] |= pack_right_shift_u16(m400_ign_cut_level_total, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_ign_cut_level_total, 0u, 0xffu);
        m400_rpm = (uint16_t)src_p->m400_rpm;
        dst_p[4] |= pack_right_shift_u16(m400_rpm, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_rpm, 0u, 0xffu);
        m400_throttle_position = (uint16_t)src_p->m400_throttle_position;
        dst_p[6] |= pack_right_shift_u16(m400_throttle_position, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_throttle_position, 0u, 0xffu);
        break;

    case 5:
        m400_gear = (uint16_t)src_p->m400_gear;
        dst_p[2] |= pack_right_shift_u16(m400_gear, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_gear, 0u, 0xffu);
        m400_gear_det = (uint16_t)src_p->m400_gear_det;
        dst_p[4] |= pack_right_shift_u16(m400_gear_det, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_gear_det, 0u, 0xffu);
        m400_gear_sensor_voltage = (uint16_t)src_p->m400_gear_sensor_voltage;
        dst_p[6] |= pack_right_shift_u16(m400_gear_sensor_voltage, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_gear_sensor_voltage, 0u, 0xffu);
        break;

    case 6:
        m400_fuel_cut_level_total = (uint16_t)src_p->m400_fuel_cut_level_total;
        dst_p[2] |= pack_right_shift_u16(m400_fuel_cut_level_total, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_fuel_cut_level_total, 0u, 0xffu);
        m400_fuel_overall_trim = (uint16_t)src_p->m400_fuel_overall_trim;
        dst_p[4] |= pack_right_shift_u16(m400_fuel_overall_trim, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_fuel_overall_trim, 0u, 0xffu);
        m400_ign_overall_trim = (uint16_t)src_p->m400_ign_overall_trim;
        dst_p[6] |= pack_right_shift_u16(m400_ign_overall_trim, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_ign_overall_trim, 0u, 0xffu);
        break;

    case 7:
        m400_la1_aim_value = (uint16_t)src_p->m400_la1_aim_value;
        dst_p[2] |= pack_right_shift_u16(m400_la1_aim_value, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(m400_la1_aim_value, 0u, 0xffu);
        m400_la1_short_term_trim = (uint16_t)src_p->m400_la1_short_term_trim;
        dst_p[4] |= pack_right_shift_u16(m400_la1_short_term_trim, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u16(m400_la1_short_term_trim, 0u, 0xffu);
        m400_lambda1 = (uint16_t)src_p->m400_lambda1;
        dst_p[6] |= pack_right_shift_u16(m400_lambda1, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u16(m400_lambda1, 0u, 0xffu);
        break;

    default:
        break;
    }

    return (8);
}

int CAN0_m400_data_set1_unpack(
    struct CAN0_m400_data_set1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t m400_drive_speed;
    uint16_t m400_drive_speed_left;
    uint16_t m400_drive_speed_right;
    uint16_t m400_fuel_cut_level_total;
    uint16_t m400_fuel_overall_trim;
    uint16_t m400_gear;
    uint16_t m400_gear_det;
    uint16_t m400_gear_sensor_voltage;
    uint16_t m400_ground_speed;
    uint16_t m400_ground_speed_left;
    uint16_t m400_ground_speed_right;
    uint16_t m400_ign_cut_level_total;
    uint16_t m400_ign_overall_trim;
    uint16_t m400_la1_aim_value;
    uint16_t m400_la1_short_term_trim;
    uint16_t m400_lambda1;
    uint16_t m400_rpm;
    uint16_t m400_tc_ignretard;
    uint16_t m400_tc_launch_aim_rpm;
    uint16_t m400_tc_power_reduction;
    uint16_t m400_tc_slip_aim_error;
    uint16_t m400_tc_slip_aim_value;
    uint16_t m400_throttle_position;
    uint16_t m400_wheel_slip;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->m400_row_counter_data_set1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    switch (dst_p->m400_row_counter_data_set1) {

    case 0:
        m400_drive_speed = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_drive_speed |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_drive_speed = (int16_t)m400_drive_speed;
        m400_drive_speed_left = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_drive_speed_left |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_drive_speed_left = (int16_t)m400_drive_speed_left;
        m400_drive_speed_right = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_drive_speed_right |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_drive_speed_right = (int16_t)m400_drive_speed_right;
        break;

    case 1:
        m400_ground_speed = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_ground_speed |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_ground_speed = (int16_t)m400_ground_speed;
        m400_ground_speed_left = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_ground_speed_left |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_ground_speed_left = (int16_t)m400_ground_speed_left;
        m400_ground_speed_right = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_ground_speed_right |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_ground_speed_right = (int16_t)m400_ground_speed_right;
        break;

    case 2:
        m400_tc_ignretard = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_tc_ignretard |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_tc_ignretard = (int16_t)m400_tc_ignretard;
        m400_tc_launch_aim_rpm = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_tc_launch_aim_rpm |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_tc_launch_aim_rpm = (int16_t)m400_tc_launch_aim_rpm;
        m400_tc_power_reduction = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_tc_power_reduction |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_tc_power_reduction = (int16_t)m400_tc_power_reduction;
        break;

    case 3:
        m400_tc_slip_aim_error = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_tc_slip_aim_error |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_tc_slip_aim_error = (int16_t)m400_tc_slip_aim_error;
        m400_tc_slip_aim_value = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_tc_slip_aim_value |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_tc_slip_aim_value = (int16_t)m400_tc_slip_aim_value;
        m400_wheel_slip = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_wheel_slip |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_wheel_slip = (int16_t)m400_wheel_slip;
        break;

    case 4:
        m400_ign_cut_level_total = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_ign_cut_level_total |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_ign_cut_level_total = (int16_t)m400_ign_cut_level_total;
        m400_rpm = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_rpm |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_rpm = (int16_t)m400_rpm;
        m400_throttle_position = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_throttle_position |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_throttle_position = (int16_t)m400_throttle_position;
        break;

    case 5:
        m400_gear = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_gear |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_gear = (int16_t)m400_gear;
        m400_gear_det = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_gear_det |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_gear_det = (int16_t)m400_gear_det;
        m400_gear_sensor_voltage = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_gear_sensor_voltage |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_gear_sensor_voltage = (int16_t)m400_gear_sensor_voltage;
        break;

    case 6:
        m400_fuel_cut_level_total = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_fuel_cut_level_total |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_fuel_cut_level_total = (int16_t)m400_fuel_cut_level_total;
        m400_fuel_overall_trim = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_fuel_overall_trim |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_fuel_overall_trim = (int16_t)m400_fuel_overall_trim;
        m400_ign_overall_trim = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_ign_overall_trim |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_ign_overall_trim = (int16_t)m400_ign_overall_trim;
        break;

    case 7:
        m400_la1_aim_value = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        m400_la1_aim_value |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        dst_p->m400_la1_aim_value = (int16_t)m400_la1_aim_value;
        m400_la1_short_term_trim = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
        m400_la1_short_term_trim |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
        dst_p->m400_la1_short_term_trim = (int16_t)m400_la1_short_term_trim;
        m400_lambda1 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
        m400_lambda1 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
        dst_p->m400_lambda1 = (int16_t)m400_lambda1;
        break;

    default:
        break;
    }

    return (0);
}

uint8_t CAN0_m400_data_set1_m400_row_counter_data_set1_encode(double value)
{
    return (uint8_t)(value);
}

double CAN0_m400_data_set1_m400_row_counter_data_set1_decode(uint8_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set1_m400_row_counter_data_set1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_la1_aim_value_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double CAN0_m400_data_set1_m400_la1_aim_value_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool CAN0_m400_data_set1_m400_la1_aim_value_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_fuel_cut_level_total_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set1_m400_fuel_cut_level_total_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set1_m400_fuel_cut_level_total_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_gear_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set1_m400_gear_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set1_m400_gear_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_ign_cut_level_total_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set1_m400_ign_cut_level_total_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set1_m400_ign_cut_level_total_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_tc_slip_aim_error_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set1_m400_tc_slip_aim_error_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set1_m400_tc_slip_aim_error_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_tc_ignretard_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set1_m400_tc_ignretard_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set1_m400_tc_ignretard_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_ground_speed_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set1_m400_ground_speed_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set1_m400_ground_speed_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_drive_speed_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set1_m400_drive_speed_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set1_m400_drive_speed_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_la1_short_term_trim_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double CAN0_m400_data_set1_m400_la1_short_term_trim_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool CAN0_m400_data_set1_m400_la1_short_term_trim_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_fuel_overall_trim_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set1_m400_fuel_overall_trim_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set1_m400_fuel_overall_trim_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_gear_det_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set1_m400_gear_det_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set1_m400_gear_det_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_rpm_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set1_m400_rpm_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set1_m400_rpm_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_tc_slip_aim_value_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set1_m400_tc_slip_aim_value_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set1_m400_tc_slip_aim_value_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_tc_launch_aim_rpm_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set1_m400_tc_launch_aim_rpm_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set1_m400_tc_launch_aim_rpm_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_ground_speed_left_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set1_m400_ground_speed_left_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set1_m400_ground_speed_left_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_drive_speed_left_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set1_m400_drive_speed_left_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set1_m400_drive_speed_left_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_lambda1_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double CAN0_m400_data_set1_m400_lambda1_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool CAN0_m400_data_set1_m400_lambda1_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_ign_overall_trim_encode(double value)
{
    return (int16_t)(value);
}

double CAN0_m400_data_set1_m400_ign_overall_trim_decode(int16_t value)
{
    return ((double)value);
}

bool CAN0_m400_data_set1_m400_ign_overall_trim_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_gear_sensor_voltage_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double CAN0_m400_data_set1_m400_gear_sensor_voltage_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool CAN0_m400_data_set1_m400_gear_sensor_voltage_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_throttle_position_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set1_m400_throttle_position_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set1_m400_throttle_position_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_wheel_slip_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set1_m400_wheel_slip_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set1_m400_wheel_slip_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_tc_power_reduction_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set1_m400_tc_power_reduction_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set1_m400_tc_power_reduction_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 750));
}

int16_t CAN0_m400_data_set1_m400_ground_speed_right_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set1_m400_ground_speed_right_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set1_m400_ground_speed_right_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t CAN0_m400_data_set1_m400_drive_speed_right_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double CAN0_m400_data_set1_m400_drive_speed_right_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool CAN0_m400_data_set1_m400_drive_speed_right_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}
